FROM node:14.14.0-alpine

WORKDIR '/app'

COPY ./package.json ./
RUN npm install
COPY . .
CMD [ "npm", "run", "dev"] 

# nodemon is a little package that reloads your project whenver the code has changed, and is used by the npm run dev